### PR TITLE
[#514] fix contains('..') in path in jar file

### LINKED ISSUE #514: Fix code scanning alert related to ".." path scanning
Tracking issue for issue code-scanning number 1

### PR DESCRIPTION
**Pull request by laurentschoelens**
Fixes #514

Change `startsWith("..")` and `startsWith("/")` to true path validation (make sure the file is written in same directory as expected

### CODE REVIEW

File: maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/JarScanner.java [hunk 1]
```diff
@@ -52,9 +54,9 @@ public void scan() {
             while (jarFileEntries.hasMoreElements()) {
                 JarEntry entry = jarFileEntries.nextElement();
                 String name = entry.getName();
-                if (name.startsWith("..") || name.startsWith("/")) {
-                    // ignore "zip slip" file pattern attack
-                    continue;
+                File file = new File(destinationDir, entry.getName());
+                if (!file.toPath().normalize().startsWith(destinationDir.toPath())) {
```
Comment (mattrpav) [inline maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/JarScanner.java:58]: Should we look for contains '..' ?

Comment (laurentschoelens) [reply maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/JarScanner.java:58]: By normalizing the path, this will check that final path is not outside the `destinationDir` (if contains .. and makes it go outside the `destinationDir`, file will be refused)
